config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }

  authenticated(:user) { root 'upload#index', as: :authenticated_root }
  devise_scope(:user) { root to: 'devise/sessions#new' }

  resources :upload, only: %i[] do
    collection do
      post :import
      get :processing
      get :success
      get :data_rules
    end
  end

  resources :passwords, only: %i[new create] do
    collection do
      get '/', to: redirect('/')
      get :success
      get :reset
      post :send_confirmation_code
      get :confirm_reset
      post :change
    end
  end

  scope controller: 'static_pages' do
    get :cookies
    get :accessibility_statement
  end

  scope controller: 'application' do
    get :build_id
    get :health
  end

  get :service_unavailable, to: 'errors#service_unavailable'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/503', to: 'errors#service_unavailable', via: :all
end

app/views/layouts/_cookie_control.html.erb
<%= javascript_tag nonce: true do -%>
  var gaID = '<%= ENV['GOOGLE_ANALYTICS_ID'] %>';
  var apiKey = '<%= ENV['COOKIE_CONTROL_API_KEY'] %>';
  var product = '<%= ENV['COOKIE_CONTROL_PRODUCT'] %>';
  var serviceName = '<%= service_name %>';
  var cookiesPath = '<%= cookies_path %>';

  var introText = 'Cookies are files saved on your phone, tablet or computer when you visit a website. \n We use cookies to store information about how you use the '
                  + serviceName + ' website, such as the pages you visit.'
  var necessaryDescription = 'Necessary cookies enable core functionality. The website cannot function properly without these cookies, and they can only be deactivated by changing your browser preferences.'
  var cookiesDescription = "We use Google Analytics to measure how you use the website so we can improve it based on user needs. Google Analytics sets cookies that store anonymised information about how you got to the site, the pages you visit, how long you spend on each page and what you click on while you're visiting the site."

  // Remove 'Accept Recommended Settings' button from DOM
  function hideAcceptButton() {
	  var recommendedSettingsButton = document.getElementById("ccc-button-holder");
	  if (recommendedSettingsButton) {
      recommendedSettingsButton.parentNode.removeChild(recommendedSettingsButton);
    }
  }

  var config = {
    apiKey: apiKey,
    product: product,
    position: 'left',
    initialState: 'open',
    onLoad: hideAcceptButton,
    sameSiteCookie: true,
    rejectButton: false,
    closeStyle: 'button',
    text: {
      title: 'This site uses cookies',
      intro:  introText,
      necessaryTitle: 'Necessary Cookies',
      necessaryDescription: necessaryDescription,
      acceptRecommended: "",
      closeLabel: "Save and close"
    },
    branding: {
      fontColor: '#333',
      backgroundColor: '#f4f4f4',
      alertBackground: '#555',
      acceptText: '#fff',
      acceptBackground: '#000',
      toggleText: '#fff',
      toggleColor: '#000',
      toggleBackground: '#555',
      removeAbout: true
    },
    statement: {
      description: 'For more information, check the',
      name: 'cookie statement',
      url: cookiesPath,
      updated: '03/03/2020'
    },
    optionalCookies: [
      {
        recommendedState: true,
        name: 'analytics',
        label: 'Cookies that measure website use',
        description: cookiesDescription,
        cookies: ['_ga', '_gid', '_gat', '__utma', '__utmt', '__utmb', '__utmc', '__utmz', '__utmv'],
        onAccept: function(){
          dataLayer.push({'event' : 'analytics_consent_given'});
          // Add Google Analytics
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
          ga('create', gaID, 'auto');
          ga('set', 'anonymizeIp', true);
          ga('send', 'pageview');
          // End Google Analytics
        },
        onRevoke: function(){
          // Disable Google Analytics
          var disableStr = 'ga-disable-' + gaID;
          window[disableStr] = true;
          // End Google Analytics
        }
      }
    ]
  };

  CookieControl.load( config );
<% end -%>

app/views/layouts/_feedback_section.html.haml
.govuk-phase-banner
  %p.govuk-phase-banner__content
    %strong.govuk-tag.govuk-phase-banner__content__tag
      beta
    %span.govuk-phase-banner__text
      This is a new service – your
      = external_link_to('feedback',
                         Rails.configuration.x.feedback_url,
                         id: 'feedback-link')
      will help us to improve it.

app/views/layouts/_footer.html.haml
%footer.govuk-footer{role: 'contentinfo'}
  .govuk-width-container
    .govuk-footer__meta
      .govuk-footer__meta-item.govuk-footer__meta-item--grow
        %h2.govuk-visually-hidden Support links
        %ul.govuk-footer__inline-list
          %li.govuk-footer__inline-list-item
            %a.govuk-footer__link{href: cookies_path}
              Cookies
          %li.govuk-footer__inline-list-item
            %a.govuk-footer__link{href: accessibility_statement_path}
              Accessibility statement

        %svg.govuk-footer__licence-logo{focusable: "false", height: "17", role: "presentation", viewbox: "0 0 483.2 195.7", width: "41", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145", fill: "currentColor"}

        %span.govuk-footer__licence-description
          All content is available under the
          %a.govuk-footer__link{href: 'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/', rel: 'license'} Open Government Licence v3.0,
          except where otherwise stated
      .govuk-footer__meta-item
        %a.govuk-footer__link.govuk-footer__copyright-logo{href: 'https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/'}© Crown copyright

app/views/layouts/_gtm_noscript.html.erb
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= ENV['GTM_ID'] %><%= ENV['GTM_URL_OVERRIDES'] %>"
title='Google Tag Manager' height='0' width='0' style='display:none;visibility:hidden'></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

app/views/layouts/_gtm_script.html.erb
<!-- Google Tag Manager -->
<%= javascript_tag nonce: true do -%>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl<%= ENV['GTM_URL_OVERRIDES'] ? "+\'#{ENV['GTM_URL_OVERRIDES']}\'".html_safe : '' %>;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer', '<%= ENV['GTM_ID'] %>');
<% end -%>
<!-- End Google Tag Manager -->

app/views/layouts/_navbar.haml
%button.govuk-header__menu-button.govuk-js-header-toggle{'aria-controls': 'navigation',
                                                         'aria-label': 'Show or hide Top Level Navigation',
                                                         role: 'button',
                                                         type: 'button',
                                                         id: 'menu'} Menu
%nav
  %ul#navigation.govuk-header__navigation{'aria-label': 'Top Level Navigation'}
    - if user_signed_in?
      %li.govuk-header__navigation-item{class: current_path?(authenticated_root_path)}
        %a.govuk-header__link{href: authenticated_root_path, id: 'upload'}
          Upload
      %li.govuk-header__navigation-item{class: current_path?(data_rules_upload_index_path)}
        %a.govuk-header__link{href: data_rules_upload_index_path, id: 'data-rules'}
          Data rules
    %li.govuk-header__navigation-item{class: current_path?(new_user_session_path)}
      - if user_signed_in?
        = link_to('Sign out', destroy_user_session_path,
          method: :delete, class: 'govuk-header__link', id: 'sign-out')
      - else
        = link_to('Sign in', new_user_session_path, class: 'govuk-header__link', id: 'sign-in')

app/views/layouts/application.html.haml
!!!
%html{html_attrs('en')}
  %head
    %meta{charset: 'utf-8'}
    %title
      = content_for?(:title) ? yield(:title) : service_name
    = csrf_meta_tags
    = csp_meta_tag

    = render 'layouts/gtm_script' if Rails.env.production? && ENV['GTM_ID']
    - if Rails.env.production? && ENV['COOKIE_CONTROL_API_KEY'] && ENV['COOKIE_CONTROL_PRODUCT']
      %script{crossorigin: 'anonymous',
              nonce: true,
              src: 'https://cc.cdn.civiccomputing.com/9/cookieControl-9.1.min.js',
              type: 'text/javascript'}
      = render 'layouts/cookie_control'

    = stylesheet_pack_tag 'application', media: 'all', defer: true
    = javascript_pack_tag 'application', defer: true

    %meta{name: 'viewport', content:'width=device-width, initial-scale=1, viewport-fit=cover'}
    %meta{name: 'theme-color', content: '#0b0c0c'}
    %meta{'http-equiv': 'X-UA-Compatible', content: 'IE=edge'}
    %meta{content: asset_pack_url('media/images/govuk-opengraph-image.png'), property: 'og:image'}

    %link{rel: 'shortcut icon', sizes: '16x16 32x32 48x48', href: asset_pack_url('media/images/favicon.ico'), type: 'image/x-icon'}
    %link{rel: 'mask-icon', href: asset_pack_url('media/images/govuk-mask-icon.svg'), color: '#0b0c0c'}
    %link{rel: 'apple-touch-icon', sizes: '180x180', href: asset_pack_url('media/images/govuk-apple-touch-icon-180x180.png')}
    %link{rel: 'apple-touch-icon', sizes: '167x167', href: asset_pack_url('media/images/govuk-apple-touch-icon-167x167.png')}
    %link{rel: 'apple-touch-icon', sizes: '152x152', href: asset_pack_url('media/images/govuk-apple-touch-icon-152x152.png')}
    %link{rel: 'apple-touch-icon', href: asset_pack_url('media/images/govuk-apple-touch-icon.png')}

  %body.govuk-template__body
    = render 'layouts/gtm_noscript' if Rails.env.production? && ENV['GTM_ID']
    = render 'layouts/header'
    .govuk-width-container
      = render 'layouts/feedback_section'
      = yield
    = render 'layouts/footer'